version: '3'
services:
    node:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/usr/src/app
        command: sh -c "yarn start"
        ports:
            - "3000:3000"
    dbapi:
        build:
            context: ./backend/go
            dockerfile: Dockerfile
        links:
            - mongodb
        depends_on:
            - mongodb
        ports:
            - "9090:9090"
        environment:
            - MONGO_URI=mongodb://mongodb:27017/mydb
    mongodb:
        image: mongo
        container_name: mongodb
        volumes:
            - mongodata:/data/db
            - ./mongo/migration.js:/docker-entrypoint-initdb.d/migration.js
        ports:
            - "27017:27017"
volumes:
    mongodata:
        driver: local